In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3], dtype='int32')
print(a)

In [ ]:
b = np.array([[1.0,2.0,3.0],[5.0,6.0,7.0]], dtype='int32')
print(b)

In [ ]:
a.ndim

In [ ]:
b.ndim

In [ ]:
a.size

In [ ]:
a.itemsize

In [ ]:
a.shape

In [ ]:
a.dtype

In [ ]:
a = np.array([[1,2,3,4,5,6,7,15,16],[8,9,10,11,12,13,14,17,18]])

In [ ]:
a[0,:]

In [ ]:
a[:, 1]

In [ ]:
a[1,1]

In [ ]:
a[0, 2:8:2]

In [ ]:
a[0,4] = 20
print(a)

In [ ]:
a[:,4] = [1,2]
print(a)

In [ ]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [ ]:
a[0,1,1]

In [ ]:
a[:,1,1]

In [ ]:
a[1,:,1] = [1,2]

In [ ]:
a[1,:,1]

In [ ]:
np.zeros(((2,2)), dtype='int32')

In [ ]:
np.ones((2,3))

In [ ]:
np.full((2,3), 7)

In [ ]:
np.full_like(a, 3)

In [ ]:
np.random.rand(3,4)

In [ ]:
np.random.randint(3,4, size=(2,2))

In [ ]:
np.identity(6)

In [ ]:
arr = np.array([[1,2],[3,4]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

In [ ]:
a = np.ones(((5,5)), dtype='int32')
b = np.zeros(((3,3)), dtype='int32')
b[1,1] = 9
a[1:-1,1:-1] = b
print(a)


In [ ]:
a = np.array([[1,2,3,4]])
a

In [ ]:
a = np.array([[1,2,3,4]])
b = a.copy()
b[0,3] = 10
b

In [ ]:
b = np.array([[1,0,1,0]])
a + b

In [ ]:
a * 2

In [ ]:
a ** 2

In [ ]:
a / 2

In [ ]:
np.cos(a)

In [ ]:
a = np.full((2,3), 3)

b = np.full((3,2), 2)

In [ ]:
np.matmul(a,b)

In [ ]:
c = np.identity(3)

In [ ]:
np.linalg.det(c)

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Dot product
print(np.dot(a, b))  

# Multi dot product
print(np.linalg.multi_dot([a, b, a]))  

# Vector dot product
print(np.vdot(a, b))  

# Inner product
print(np.inner(a, b))  

# Outer product
print(np.outer(a, b))  

# Matrix product
print(np.matmul(a, b))  

# Matrix-vector product
v = np.array([1, 2])
print(np.matmul(a, v))  

# Tensor dot product
print(np.tensordot(a, b))  

# Einstein summation
print(np.einsum('ij,jk->ik', a, b))  

# Kronecker product
print(np.kron(a, b))  

# Cross product (for 3D vectors)
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(np.cross(v1, v2))  


In [ ]:
A = np.array([[4, 12], [7, 15]])

# Cholesky decomposition
print(np.linalg.cholesky(A))  

# QR decomposition
q, r = np.linalg.qr(A)
print(q, r)  

# SVD decomposition
U, S, Vt = np.linalg.svd(A)
print(U, S, Vt)  


In [ ]:
# Eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(A)
print(eigvals, eigvecs)  

# Only eigenvalues
print(np.linalg.eigvals(A))  


In [ ]:
# Matrix norm
print(np.linalg.norm(A))  

# Determinant
print(np.linalg.det(A))  

# Rank of matrix
print(np.linalg.matrix_rank(A))  

# Trace (sum of diagonals)
print(np.trace(A))  


In [ ]:
B = np.array([[3], [5]])

# Solve Ax = B
x = np.linalg.solve(A, B)
print(x)  

# Inverse of a matrix
print(np.linalg.inv(A))  

# Pseudo-inverse (Moore-Penrose)
print(np.linalg.pinv(A))  


In [ ]:
# Diagonal elements
print(np.diagonal(A))  

# Transpose
print(A.T)  


In [ ]:
import numpy as np

# Define matrices for testing
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.array([[2, 3], [4, 5]])
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# Matrix operations
dot_product = np.dot(a, b)
multi_dot_product = np.linalg.multi_dot([a, b, c])
vdot_product = np.vdot(a, b)
inner_product = np.inner(a, b)
outer_product = np.outer(a, b)
matmul_product = np.matmul(a, b)
tensordot_product = np.tensordot(a, b, axes=1)
einsum_product = np.einsum('ij,jk->ik', a, b)
kron_product = np.kron(a, b)
cross_product = np.cross(v1, v2)

# Decompositions
A = np.array([[4, 12], [7, 15]])
cholesky_decomp = np.linalg.cholesky(A)
q, r = np.linalg.qr(A)
U, S, Vt = np.linalg.svd(A)

# Eigenvalues and vectors
eigvals, eigvecs = np.linalg.eig(A)

# Norms and matrix properties
matrix_norm = np.linalg.norm(A)
determinant = np.linalg.det(A)
matrix_rank = np.linalg.matrix_rank(A)
trace_value = np.trace(A)

# Solving equations and inverses
B = np.array([[3], [5]])
solution = np.linalg.solve(A, B)
inverse_matrix = np.linalg.inv(A)
pseudo_inverse = np.linalg.pinv(A)

# Other matrix operations
diagonal_values = np.diagonal(A)
transpose_matrix = A.T

# Compile results
results = {
    "dot_product": dot_product,
    "multi_dot_product": multi_dot_product,
    "vdot_product": vdot_product,
    "inner_product": inner_product,
    "outer_product": outer_product,
    "matmul_product": matmul_product,
    "tensordot_product": tensordot_product,
    "einsum_product": einsum_product,
    "kron_product": kron_product,
    "cross_product": cross_product,
    "cholesky_decomp": cholesky_decomp,
    "qr_decomp_Q": q,
    "qr_decomp_R": r,
    "svd_U": U,
    "svd_S": S,
    "svd_Vt": Vt,
    "eigvals": eigvals,
    "eigvecs": eigvecs,
    "matrix_norm": matrix_norm,
    "determinant": determinant,
    "matrix_rank": matrix_rank,
    "trace_value": trace_value,
    "solution": solution,
    "inverse_matrix": inverse_matrix,
    "pseudo_inverse": pseudo_inverse,
    "diagonal_values": diagonal_values,
    "transpose_matrix": transpose_matrix,
}

results


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

In [ ]:
np.min(a)

In [ ]:
np.max(a)

In [ ]:
np.sum(a, axis=0)

In [ ]:
np.sum(a, axis=1)

In [ ]:
a.reshape((2,2,2))

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

np.vstack([a,b,a,b])
np.hstack([a,b,a,b])

In [84]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')

print(filedata)

(~((filedata > 10) & (filedata < 20)))

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


array([[ True, False,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False, False],
       [ True,  True,  True, False,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [ ]:
filedata[filedata > 50]
filedata[[0,1,2]]

In [86]:
np.any(filedata > 50, axis=0)
np.any(filedata > 50, axis=1)

array([ True,  True,  True])

In [87]:
np.all(filedata > 50, axis=0)
np.all(filedata > 50, axis=1)

array([False, False, False])